In [34]:
from google.colab import files
uploaded = files.upload()

Saving kmers_ari_v_5.py to kmers_ari_v_5.py


In [0]:
from kmers_ari_v_5 import kmers

In [74]:
import numpy as np

string = 'ATCGCATCATCGTTATCAGTC'
print (type(string))
k = 3 
s = 1
obj = kmers(k) 
string_vector = obj.kmer_one_string(string,s, count_occurrences=True)

<class 'str'>


In [75]:
string_vector

array([0., 0., 0., 0., 0., 0., 4., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 2., 0., 0., 2., 0., 0., 0., 0., 0., 2.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
!pip install pyfastx
import pyfastx
from google.colab import files
uploaded = files.upload()

In [0]:
fa = pyfastx.Fasta('GCF_000008865.2_ASM886v2_genomic.fa')
seq = fa[0]

In [0]:
k = 2  
s = 1
obj = kmers(k) 
dna_vector = obj.kmer_list_m_strings(seq, count_occurrences=True)

In [89]:
dna_vector

array([[ 7.,  4.,  4., ...,  3.,  6.,  4.],
       [12.,  7.,  3., ...,  6.,  3.,  4.],
       [ 2.,  8.,  6., ...,  4.,  0.,  6.],
       ...,
       [ 6.,  9.,  2., ...,  4.,  5.,  4.],
       [ 6.,  8.,  2., ...,  3.,  6.,  4.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [90]:
dna_vector.size

18560

In [91]:
len(dna_vector) # this is the number of lines in the DNA sequence

1160

In [98]:
c = 1
print ('dna vector lenght is 4^k = ',len(dna_vector[1]))
for line in range (len(dna_vector)):
   print ('%5i)' %c,dna_vector[line])
   c = c+1
   if c > 15: break

dna vector lenght is 4^k =  16
    1) [7. 4. 4. 7. 3. 4. 4. 5. 6. 6. 9. 2. 5. 3. 6. 4.]
    2) [12.  7.  3.  3.  6.  3.  4.  6.  2.  3.  5.  6.  6.  6.  3.  4.]
    3) [2. 8. 6. 1. 5. 6. 9. 4. 6. 7. 8. 3. 4. 4. 0. 6.]
    4) [12.  8.  4.  6.  6.  3.  4.  5.  6.  3.  1.  3.  6.  4.  3.  5.]
    5) [7. 8. 5. 4. 5. 3. 4. 7. 7. 4. 3. 2. 5. 4. 4. 7.]
    6) [ 6.  4.  2.  5.  4. 12.  6.  6.  2.  4.  2.  5.  5.  8.  3.  5.]
    7) [8. 5. 5. 2. 4. 3. 9. 7. 4. 7. 2. 4. 3. 8. 1. 7.]
    8) [ 6.  6.  5.  2.  4.  7.  3. 11.  4.  8.  2.  2.  4.  4.  7.  4.]
    9) [5. 9. 2. 5. 4. 4. 4. 8. 5. 3. 2. 4. 6. 4. 6. 8.]
   10) [6. 7. 5. 5. 2. 9. 4. 5. 7. 3. 8. 2. 7. 2. 3. 4.]
   11) [ 7.  8.  5.  6. 10.  7.  2.  5.  3.  3.  4.  3.  6.  6.  2.  2.]
   12) [ 9.  9.  1.  5.  4.  4.  3.  9.  6.  0.  1.  2.  5.  7.  4. 10.]
   13) [ 6.  8.  3.  7. 10.  5.  2.  4.  6.  3.  2.  3.  2.  5.  7.  6.]
   14) [ 4.  8.  1.  4.  7.  7.  4.  6.  4.  3.  4.  3.  3.  5.  5. 11.]
   15) [ 4.  9.  0.  5.  5.  9.  7.  9.  6.

In [99]:
dna_vector #(1160*(4^k))

array([[ 7.,  4.,  4., ...,  3.,  6.,  4.],
       [12.,  7.,  3., ...,  6.,  3.,  4.],
       [ 2.,  8.,  6., ...,  4.,  0.,  6.],
       ...,
       [ 6.,  9.,  2., ...,  4.,  5.,  4.],
       [ 6.,  8.,  2., ...,  3.,  6.,  4.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [86]:
#k = 4  
s = 1
test = 'GGGG'
k = len(test)
obj = kmers(k) 
print (test, 'in digits' ,obj.kmer_digits(test))
numbering, onehot_vector = obj.kmer_number(test)
print (test, 'one hot vector of lenght' ,len(onehot_vector))
print (onehot_vector)
print ('number', numbering, 'over', pow(4,k) )
#obj.kmer_number(test)

GGGG in digits [3 3 3 3]
GGGG one hot vector of lenght 256
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
number 255 over 256
